### ISSUE TITLE
[BUG] WPOnion Not Working inside Theme

### ISSUE THREAD

**Issue by Tzvook** [wponion/wponion#124]
Hi
Demo looks good, but whatever I do I can't connect it to my theme ... I spent days on it with no success ..

Basically I use this @ functions.php

```
require_once __DIR__.'/wponion/wponion.php';
function bsOnion_after_wponion_loaded(){
    //do your stuff here.
require_once dirname( __FILE__ ) .'/wponion-config/index.php';
}
add_action( 'wponion_loaded', 'bsOnion_after_wponion_loaded' );
```

the "wponion-config/index.php" dir includes your demo plugin code ..
am I missing something ?

replacing it with any of your code samples don't work ..

**Comment by varunsridharan** [comment]
Hello There

Thanks for checking out WPOnion and well code which you used is correct but wponion cannot be loaded via theme it should be loaded via plugin only. 

We done support theme because WordPress.org does not allow themes to pack a framework with it. 

So i request you to use a plugin. also make sure you run `composer install` inside wponion folder to install its required libs.
